version: '3'

services:

  # P2p section
  bootnode:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_TYPE=bootnode
    volumes:
      - bootnode-keys:/keys
    networks:
      mev-net:
        ipv4_address: 172.28.0.2
    profiles:
      - p2pnode

  provider:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - bootnode
    environment:
      - NODE_TYPE=provider
    volumes:
      - provider-keys:/keys
    networks:
      - mev-net
    profiles:
      - p2pnode

  user:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - bootnode
    environment:
      - NODE_TYPE=user
    volumes:
      - user-keys:/keys
    networks:
      - mev-net
    ports:
      - "13523:13523"
      - "13524:13524"
    profiles:
      - p2pnode


  # Settlement layer section
  coordinator:
    build: 
      context: ./op-docker/coordinator
    environment:
      - DEPLOYMENT_CONTEXT=${DEPLOYMENT_CONTEXT}
      - L1_BLOCK_TIME=${L1_BLOCK_TIME}
      - L2_BLOCK_TIME=${L2_BLOCK_TIME}
      - GOVERNANCE_TOKEN_SYMBOL=${GOVERNANCE_TOKEN_SYMBOL}
      - GOVERNANCE_TOKEN_NAME=${GOVERNANCE_TOKEN_NAME}
    volumes:
      - shared-optimism:/shared-optimism
    networks:
      - op-net
    profiles:
      - settlement
  l1-geth:
    build: 
      context: ./op-docker/l1-geth
    volumes:
      - shared-optimism:/shared-optimism
    networks:
      - op-net
    ports:
      - "8544:8545"
    profiles:
      - settlement
  op-geth:
    build: 
      context: ./op-docker/op-geth
    volumes:
      - shared-optimism:/shared-optimism
    networks:
      - op-net
    ports:
      - "8545:8545"
    profiles:
      - settlement
  op-node:
    build:
      context: ./op-docker/op-node
    volumes:
      - shared-optimism:/shared-optimism
    networks:
      - op-net
    ports:
      - "8546:8545"
    profiles:
      - settlement
  op-batcher:
    build:
      context: ./op-docker/op-batcher
    networks:
      - op-net
    profiles:
      - settlement
  op-proposer:
    build:
      context: ./op-docker/op-proposer
    volumes:
      - shared-optimism:/shared-optimism
    networks:
      - op-net
    profiles:
      - settlement

volumes:
  bootnode-keys:
  provider-keys:
  user-keys:
  shared-optimism:

networks:
  mev-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  op-net:
    driver: bridge
