version: '3'

services:
  bootnode:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: bootnode
    restart: always
    volumes:
      - ./integrationtest/keys/bootnode:/key
    depends_on:
      - funder
    networks:
      primev_net:
        ipv4_address: 172.29.18.2
    ports:
      - "8080:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - non-datadog
      - minimal_setup
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  provider-1:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: provider
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/provider1:/key
    networks:
      - primev_net
    ports:
      - "8081:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - non-datadog
      - minimal_setup
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  provider-emulator-1:
    build:
      context: .
      dockerfile: ./integrationtest/provider/Dockerfile
    restart: always
    depends_on:
      - provider-1
    environment:
      - PROVIDER_IP=provider-1:13524
    networks:
      - primev_net
    ports:
      - "8082:8080"
    profiles:
      - non-datadog
      - minimal_setup
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  provider-2:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: provider
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/provider2:/key
    networks:
      - primev_net
    ports:
      - "8083:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - non-datadog
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  provider-emulator-2:
    build:
      context: .
      dockerfile: ./integrationtest/provider/Dockerfile
    restart: always
    depends_on:
      - provider-2
    environment:
      - PROVIDER_IP=provider-2:13524
    networks:
      - primev_net
    ports:
      - "8084:8080"
    profiles:
      - non-datadog
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  provider-3:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: provider
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/provider3:/key
    networks:
      - primev_net
    ports:
      - "8085:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - non-datadog
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  provider-emulator-3:
    build:
      context: .
      dockerfile: ./integrationtest/provider/Dockerfile
    restart: always
    depends_on:
      - provider-3
    environment:
      - PROVIDER_IP=provider-3:13524
    networks:
      - primev_net
    ports:
      - "8086:8080"
    profiles:
      - non-datadog
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  user-1:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: user
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/user1:/key
    networks:
      - primev_net
    ports:
      - "8087:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - non-datadog
      - minimal_setup
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  user-emulator-1:
    build:
      context: .
      dockerfile: ./integrationtest/user/Dockerfile
    restart: always
    depends_on:
      - user-1
    env_file:
      - integrationtest/.env
    environment:
      - USER_IP=user-1:13524
    networks:
      - primev_net
    ports:
      - "8088:8080"
    profiles:
      - non-datadog
      - minimal_setup
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  user-2:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: user
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/user2:/key
    networks:
      - primev_net
    ports:
      - "8089:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - non-datadog
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  user-emulator-2:
    build:
      context: .
      dockerfile: ./integrationtest/user/Dockerfile
    restart: always
    depends_on:
      - user-2
    env_file:
      - integrationtest/.env
    environment:
      - USER_IP=user-2:13524
    networks:
      - primev_net
    ports:
      - "8090:8080"
    profiles:
      - non-datadog
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  user-3:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: user
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/user3:/key
    networks:
      - primev_net
    ports:
      - "8091:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - non-datadog
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  user-emulator-3:
    build:
      context: .
      dockerfile: ./integrationtest/user/Dockerfile
    restart: always
    depends_on:
      - user-3
    env_file:
      - integrationtest/.env
    environment:
      - USER_IP=user-3:13524
    networks:
      - primev_net
    ports:
      - "8092:8080"
    profiles:
      - non-datadog
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  user-4:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: user
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/user4:/key
    networks:
      - primev_net
    ports:
      - "8093:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - non-datadog
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  user-emulator-4:
    build:
      context: .
      dockerfile: ./integrationtest/user/Dockerfile
    restart: always
    depends_on:
      - user-4
    env_file:
      - integrationtest/.env
    environment:
      - USER_IP=user-4:13524
    networks:
      - primev_net
    ports:
      - "8094:8080"
    profiles:
      - non-datadog
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  user-5:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: user
    restart: always
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/user5:/key
    networks:
      - primev_net
    ports:
      - "8095:13523"
    env_file:
      - integrationtest/.env
    profiles:
      - non-datadog
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  user-emulator-5:
    build:
      context: .
      dockerfile: ./integrationtest/user/Dockerfile
    restart: always
    depends_on:
      - user-5
    env_file:
      - integrationtest/.env
    environment:
      - USER_IP=user-5:13524
    networks:
      - primev_net
    ports:
      - "8096:8080"
    profiles:
      - non-datadog
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  funder:
    build:
      context: ./integrationtest/foundry
    env_file:
      - integrationtest/.env
    networks:
      - primev_net
    profiles:
      - non-datadog
      - minimal_setup

  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=${DD_KEY}
      - DD_TAGS=env:test
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE="name:datadog-agent"
    networks:
      primev_net:
        ipv4_address: 172.29.58.3
    profiles:
      - datadog

networks:
  primev_net:
    external: true
