priv_key_file: /key
peer_type: bidder
p2p_port: 13522
http_port: 13523
rpc_port: 13524
secret: hello
log_fmt: json
log_level: debug
provider_registry_contract: <PROVIDER_REGISTRY>
rpc_endpoint: <RPC_URL>
bootnodes:
  - /ip4/172.29.18.2/tcp/13522/p2p/16Uiu2HAmLYUvthfDCewNMdfPhrVefBbsfaPL22fWWfC2zuoh5SpV
