priv_key_file: /keys/bootnode
peer_type: bootnode
p2p_port: 13522
http_port: 13523
rpc_port: 13524
secret: hello
log_fmt: text
log_level: debug
bidder_registry_contract: 0xb1692ab820BF196d54e21Fbb1607931558B1d077
provider_registry_contract: 0xeA73E67c2E34C4E02A2f3c5D416F59B76e7617fC
rpc_endpoint: http://localhost:8545
