priv_key_file: /keys/provider
peer_type: provider
p2p_port: 13522
http_port: 13523
rpc_port: 13524
secret: hello
log_fmt: text
log_level: debug
expose_provider_api: true
preconf_contract: 0x8C8571F28a90813f8C468E5dbCF3B53c94aCE580
provider_registry_contract: 0xeA73E67c2E34C4E02A2f3c5D416F59B76e7617fC
bidder_registry_contract: 0xb1692ab820BF196d54e21Fbb1607931558B1d077
rpc_endpoint: http://localhost:8545
bootnodes:
  - /ip4/<localhost>/tcp/13522/p2p/<p2p_ID>
